name: frontend
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/login/
    - assets/info/
    - assets/home/
    - assets/mypage/
    - assets/schedule/
    - assets/chatbot/
    - assets/routine/
  uses-material-design: true
